# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'club_manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for club_manager
pod 'KakaoSDKAuth'  # 카카오 로그인
pod 'KakaoSDKUser'
pod 'KakaoSDKCommon'
pod 'KakaoOpenSDK'

pod 'GoogleSignIn' #구글 로그인


pod 'FSCalendar'
pod "TTGTagCollectionView"

end
